JyExcelLibrary is a robotframework library which helps to interact with excel sheets using jython. Currently you can
perform the READ and WRITE operations on excel. Please go through the keyword documentation present in "Releases".

Current limitations:

   1) You cannot use this libray with python.

You can download the latest version from `here`
https://github.com/badari412/JyExcelLibrary/releases/tag/0.0.2

How to use:

Add JyExcelLibrary to Jython's classpath and import JyExcelLibrary.xml in RIDE. That's it! You can find the latest
release, keywords documentation under "Releases" tab.